# -*- coding: utf-8 -*-
"""Cat_Vs_Dog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX1z3uBTYSbe1T99VN6P7sbZYNMHHUZz

# Cat Vs Dog Model - Deep Learning
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d salader/dogsvscats

import zipfile
zip_ref=zipfile.ZipFile('/content/dogsvscats.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

# Importing libraries
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten, MaxPooling2D,Conv2D,BatchNormalization

"""# Splitting the data into train and test"""

train_dataset_raw = keras.utils.image_dataset_from_directory(
    directory='/content/train',
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(128,128)
)

train_class_names = train_dataset_raw.class_names
train_data = train_dataset_raw

test_dataset_raw = keras.utils.image_dataset_from_directory(
    directory='/content/test',
    labels='inferred',
    label_mode='int',
    batch_size=32,
    image_size=(128,128)
)

test_class_names = test_dataset_raw.class_names
test_data = test_dataset_raw

class_names = train_dataset_raw.class_names
class_names

from keras.layers import RandomFlip, RandomRotation, RandomZoom
data_aug = Sequential([
    RandomFlip("horizontal"),
    RandomRotation(0.1),
    RandomZoom(0.1)
])

def preprocess(image, label):
  image = data_aug(image)
  image = tf.cast(image, tf.float32) / 255.0

  return image, label

train_data = train_data.map(preprocess)
test_data = test_data.map(lambda x, y: (tf.cast(x, tf.float32)/255.0, y))  # only normalize test

train_data

"""# Building the CNN Model"""

from keras.layers import Input, Conv2D, BatchNormalization, MaxPooling2D
from keras.layers import Flatten, Dense, Dropout

model = Sequential()


model.add(Input(shape=(128,128,3)))

model.add(Conv2D(32, (3,3), padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(128, (3,3), padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(128, (3,3), padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

from keras.callbacks import EarlyStopping
early_stop = EarlyStopping(patience=3, restore_best_weights=True)

history = model.fit(train_data,validation_data=test_data,epochs=20,callbacks=[early_stop])

import matplotlib.pyplot as plt
plt.plot(history.history['val_loss'],color='g')
plt.plot(history.history['loss'],color='b')
plt.show()

import matplotlib.pyplot as plt
plt.plot(history.history['val_accuracy'],color='g')
plt.plot(history.history['accuracy'],color='b')
plt.show()

"""# Testing the model"""

import cv2

img=cv2.imread('catyy.jpg')

plt.imshow(img)

img.shape

img = cv2.resize(img, (128, 128))
img = img / 255.0
test_input = img.reshape(1, 128, 128, 3)

print(img.shape)

print(train_class_names)

pred = model.predict(test_input)
print(pred)

if pred[0][0] > 0.5:
    print("Dog")
else:
    print("Cat")

"""Correctly predicted ---> Cat"""

a=cv2.imread('/content/bbby.jpg')

plt.imshow(a)

img = cv2.resize(a, (128, 128))
img = img / 255.0
test_input = img.reshape(1, 128, 128, 3)

print(img.shape)

img.shape

pred=model.predict(test_input)

if pred[0][0] > 0.5:
    print("Dog")
else:
    print("Cat")

"""Couldn't predict baby and wrongly predicted it as Dog"""

b=cv2.imread('/content/dooog.jpg')

plt.imshow(b)

b.shape

img = cv2.resize(b, (128, 128))
img = img / 255.0
test_input = img.reshape(1, 128, 128, 3)

print(img.shape)

model.predict(test_input)

if pred[0][0] > 0.5:
    print("Dog")
else:
    print("Cat")

"""Correctly predicted-----> Dog"""

